version: '2'
services:
      dbos:
          image: mysql:5.7
          volumes:
               - mysql_storage_new:/var/lib/mysql
          restart: always
          environment:
               MYSQL_ROOT_PASSWORD: rootpass
               MYSQL_USER: vimal
               MYSQL_PASSWORD: redhat
               MYSQL_DATABASE: mydb
        
      app:
          image: nextcloud
          ports:
               - 8080:80
          links:
               - dbos
          volumes:
               - nc_storage_new:/var/www/html
          restart: always
               
volumes:
          mysql_storage_new:
          nc_storage_new:

                                        
